
import './globals.css'
import { Inter } from 'next/font/google';
import { LoginProvider } from "./context/LoginContext";
import Outlet from './outlet';
import NavBar from './comp/NavBar/Navbar';
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <LoginProvider>
          <NavBar />
          <Outlet>
          {children}
          </Outlet>
        </LoginProvider></body>
    </html>
  )
}
